[package]
name = "grpc-binary-logger-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11"
prost-types = { version = "0.11.1", features = ["std"] }
tonic = "0.8"

[build-dependencies]
prost-build = "0.11"
tonic-build = "0.8"
